export const skillsItems = [
  {
    title: 'hard',
    items: [
      'html',
      'css',
      'javascript',
      'react',
      'stateManagement',
      'forms',
      'buildTools',
      'testing',
      'api',
      'architecture',
      'git',
      'design',
      'cms',
      'php',
      'methodologies',
      'communication',
      'english',
    ],
  },
  {
    title: 'soft',
    items: [
      'teamwork',
      'deadlines',
      'attention',
      'codeQuality',
      'timeManagement',
      'criticism',
      'conflicts',
      'communication',
      'reports',
      'remoteWork',
      'mentoring',
      'learning',
    ],
  },
]